export const TradingPairs = {
  FETCH_TRADING_PAIRS: 'FETCH_TRADING_PAIRS',
  FETCH_TRADING_PAIRS_SUCCESS: 'FETCH_TRADING_PAIRS_SUCCESS',
  FETCH_TRADING_PAIRS_FAILURE: 'FETCH_TRADING_PAIRS_FAILURE',
};
