export const TradingPairs = {
  FETCH_TRADING_PAIRS: 'FETCH_TRADING_PAIRS',
  FETCH_TRADING_PAIRS_SUCCESS: 'FETCH_TRADING_PAIRS_SUCCESS',
  FETCH_TRADING_PAIRS_FAILURE: 'FETCH_TRADING_PAIRS_FAILURE',
  SAVE_TO_FAVORITES: 'SAVE_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
  FETCH_FAVORITES: 'FETCH_FAVORITES',
  FETCH_FAVORITES_SUCCESS: 'FETCH_FAVORITES_SUCCESS',
  UPDATE_FAVORITES: 'UPDATE_FAVORITES',
};
